# Generated by Django 3.1.5 on 2021-01-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='county',
            options={},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={},
        ),
        migrations.AlterModelOptions(
            name='parish',
            options={},
        ),
        migrations.AlterModelOptions(
            name='subcounty',
            options={},
        ),
        migrations.AlterField(
            model_name='pollingstation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='pollingstation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9),
        ),
    ]
