# Generated by Django 3.1.5 on 2021-01-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_auto_20210112_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollingstation',
            name='code',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
