# Generated by Django 3.1.5 on 2021-01-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_auto_20210112_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollingstation',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='pollingstation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
